### ISSUE TITLE
chatbot profile hả bác

### ISSUE THREAD

**Issue by lehuukhoa** [Hongarc/facebook-api#1]
chatbot profile hả bác . có bị checkpoint ko bác. Cài sao bác

**Comment by Hongarc** [comment]
Nguồn ở đây bạn nhé : 
[facebook-chat-api](https://github.com/Schmavery/facebook-chat-api)

Bạn đọc tài liệu của nó và làm theo thôi, cái này mình chỉ làm lại 1 số thứ và xem cách họ làm như thế nào thôi.
Bạn có thể chạy ở local rồi tạo 1 file lưu cookie
`fs.writeFileSync('appstate.json', JSON.stringify(api.getAppState()));`
rồi lưu code vô đăng nhập ở các nơi khác như c9 hay heroku đều ko bị checkpiont.
Có gì không hiểu có thể liên hệ qua fb của mình.
